merge macos-deps scripts to reduce duplication
fix core mirror directory as well

diff --git a/scripts/development/macos-deps/clone-common b/scripts/development/macos-deps/clone-common
--- a/scripts/development/macos-deps/clone-common
+++ b/scripts/development/macos-deps/clone-common
@@ -4,21 +4,27 @@ set -o errexit
 
 MIRRORS_ROOT_DIR=/Volumes/Storage/Work/mirrors/
 
-PROJECT=zdoom-macos-deps
-REPO_URL=https://github.com/ZDoom/$PROJECT.git
+if [ -z "$PROJECT" ]; then
+	echo 'ERROR: PROJECT variable is not set'
+	exit 1
+fi
+
+if [ -z "$REPO_URL" ]; then
+	REPO_URL=https://github.com/aedi-org/$PROJECT.git
+fi
+
 MIRROR_DIR=$MIRRORS_ROOT_DIR$PROJECT
 WORK_DIR=/Volumes/ramdisk/$PROJECT
 
-CORE_PROJECT=aedi-core
-CORE_REPO_URL=https://github.com/alexey-lysiuk/$CORE_PROJECT.git
-CORE_MIRROR_DIR=$MIRRORS_ROOT_DIR$CORE_PROJECT
+CORE_REPO_URL=https://github.com/aedi-org/core.git
+CORE_MIRROR_DIR=${MIRRORS_ROOT_DIR}aedi-core
 
 if [ ! -e "$MIRROR_DIR" ]; then
 	git clone --mirror "$REPO_URL" "$MIRROR_DIR"
 fi
 
 if [ -e "$CORE_MIRROR_DIR" ]; then
-	git -C "$MIRROR_DIR" fetch --all
+	git -C "$CORE_MIRROR_DIR" fetch --all
 else
 	git clone --mirror "$CORE_REPO_URL" "$CORE_MIRROR_DIR"
 fi
diff --git a/scripts/development/macos-deps/pycharm-common b/scripts/development/macos-deps/pycharm-common
--- a/scripts/development/macos-deps/pycharm-common
+++ b/scripts/development/macos-deps/pycharm-common
@@ -2,7 +2,10 @@
 
 set -o errexit
 
-source "$(cd "${0%/*}"; pwd)/clone"
+if [ -z "$WORK_DIR" ]; then
+	echo 'ERROR: WORK_DIR variable is not set'
+	exit 1
+fi
 
 open -b com.jetbrains.pycharm.ce "$WORK_DIR"
 "$WORK_DIR/build.py" --target=build-prefix
